- name: configuring mysql-server 
  hosts: mysql 
  become: yes 
  tasks: 
  - name: installing mysql
    ansible.builtin.package:
      name: mysql-server 
      state: installed 
  - name: run mysql-server 
    ansible.builtin.service:
      name: mysqld 
      state: started 
      enabled: yes 
  - name: connect to mysql-server 
    ansible.mysql.mysql_info:
    login_user: root
    login_password: ExpenseApp@1
    login_host: 172.31.22.153
    register: mysql_info

  
  - name: print register output 
    ansible.builtin.debug: 
      msg: "{{ mysql_info }}"

      